version: '3'

networks:
  msnetwork:
    external: true

services:
  # nginx:
  #   build: images/nginx
  #   command: nginx -g "daemon off;"
  #   links:
  #     - php
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./images/php/app/public:/var/www/html/app/public
  # php:
  #   build: images/php
  #   volumes:
  #     - ./images/php:/var/www/html
  #   working_dir: /var/www/html/app/public
  #   command: php-fpm
  #   links:
  #     - db
  #     - cache
  #   ports:
  #     - "3003:3003"
  php-webserver:
    image: nginx:alpine
    container_name: php-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - msnetwork
    ports:
      - "3003:3003"
  order:
    container_name: order
    build: .
    # ports:
    #   - "3003:3003"
    working_dir: /application
    volumes:
      # - .:/var/www/order
      - .:/application
    networks:
      - msnetwork
