version: '3'

networks:
  kafka_app-net:
    external: true

services:
  nginx:
    image: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/app/html:ro
    networks:
      - kafka_app-net
