version: '3'

networks:
  msnetwork:
    external: true

services:
  auth:
    container_name: auth
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    networks:
      - msnetwork
