version: '3'

networks:
  kafka_app-net:
    external: true

services:
  auth:
    container_name: auth
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    networks:
      - kafka_app-net
