version: '3'

networks:
  msnetwork:
    external: true

services:
  mailer:
    container_name: mailer
    build: .
    volumes:
      - .:/app
    networks:
      - msnetwork
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025
    networks:
      - msnetwork
