version: '3'

networks:
  msnetwork:
    external: true

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: msdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - msnetwork
  pgadmin:
    image: dpage/pgadmin4:5.2 #@TODO - must know why isn't possible to load servers.json on newest image version
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
      - "./servers.json:/pgadmin4/servers.json"
    networks:
      - msnetwork
