version: '3'

networks:
  msnetwork:
    external: true

services:
  product:
    container_name: product
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    networks:
      - msnetwork
